config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show] #追記 ユーザーマイページへのルーティング
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'posts#top'

  get 'posts/index' => 'posts#index'
  get 'posts/new' => 'posts#new'
  post 'posts/new' => 'posts#create'
  get 'posts/:id' => 'posts#show', as: 'post'
  patch 'posts/:id' => 'posts#update'
  delete 'posts/:id' => 'posts#destroy' 
  get 'posts/:id/edit' => 'posts#edit', as: 'edit_post'

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord

    belongs_to :user
      
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy

  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 } #追記

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # 割愛
  
    # deviseコントローラーにストロングパラメータを追加する          
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      # アカウント編集の時にnameとprofileのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
  
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
  
    def create
      post = Post.find(params[:post_id])
      comment = post.comments.build(comment_params) #buildを使い、contentとpost_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path)
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path)
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
  end
  

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
      like = current_user.likes.create(post_id: params[:post_id]) #user_idとpost_idの二つを代入
      redirect_back(fallback_location: root_path)
    end
  
    def destroy
      like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
      like.destroy
      redirect_back(fallback_location: root_path)
    end
  
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :authenticate_user!
  
    def top
    end
  
    def index
      @posts = Post.all
    end
  
    def new
      @post = Post.new
    end
  
    def create
      post = Post.new(post_params)
  
      post.user_id = current_user.id
  
      if post.save
         redirect_to :action => "index"
      else
         redirect_to :action => "new"
      end
  
    end
  
    def show
      @post = Post.find(params[:id])
      @user = @post.user
      @like = Like.new
      @post.user_id = current_user.id
      @comments = @post.comments
      @comment = Comment.new
      
    end
  
    def edit
      @post = Post.find(params[:id])
    end
  
    def update
      @post = Post.find(params[:id])
      if @post.update(post_params)
        redirect_to posts_path, notice: "編集しました"
      else
        render 'edit'
      end
    end
  
    def destroy
      Post.find(params[:id]).destroy
      redirect_to posts_index_path, notice:"削除しました"
    end
  
   private
  
    def post_params
      params.require(:post).permit(:title, :body, :start_time, :out_time)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
      @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>batching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= link_to "ログイン", root_path %>
  <%= link_to "新規登録", new_user_registration_path %>
  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>

 
  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_with(model: @post, local: true) do |form| %>

    <div class="title">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
    <div class="time">
      <%= form.label :start_time %>
      <%= form.datetime_select :start_time %>
      <%= form.label :out_time %>
      <%= form.datetime_select :out_time %>
    </div>
    
    <div class="body">
      <%= form.label :body %>
      <%= form.text_field :body %>
    </div>
  
    <div class="submit">
      <%= form.submit %>
    </div>
  
<% end %>

app/views/posts/index.html.erb
<div class="index">

  <p id="notice"><%= notice %></p>

  <header class="main">

   <h1 class-"header-ttl">OP戦募集表</h1>

  </header>

  <% if user_signed_in? %>
    <%= link_to "マイページへ", user_path(current_user.id) %>　
  <% end %>
  

  <div class="sample">
      <table>
        <thead>
          <tr>
            <th>チーム名</th>
            <th>時間</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <% if current_user.already_liked?(post) %>
            　 <%=link_to post_path(post), method: :delete do%>
               <%end%>
              <% else %>
               <%=link_to post_path(post), method: :post do%>
                <p>申込</p><%=post.likes.count%>
            　 <%end%>
              <% end %>
              
              <td><%= post.title %></td>
              <td><%= post.start_time %></td>
              <td><%= post.out_time%></td>
              <td><%= link_to '詳細', post_path(post.id) %></td>
              <td><%= link_to '編集する', edit_post_path(post.id) %></td>
              <td><%= link_to '削除',post_path(post.id), method: :delete, data: { confirm: '削除しますか?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

     <br>


     <p><%= link_to '募集する', posts_new_path %></p>


    <%= month_calendar events: @posts do |date, psots| %>
      <%= date.day %>
    
      <% @posts.each do |post| %>
        <div>
          <%= link_to post.title, post %>
        </div>
      <% end %>
    <% end %>
      

  </div>
</div>

app/views/posts/new.html.erb
<%= form_with(model: @post, local: true, url:posts_new_path) do |form| %>
 <body>
  <div class="first-block1">
  　<h3>
    <div class="チーム名">
      <%= form.label :チーム名 %>
      <%= form.text_field :チーム名 %>
    </div>
  
    <div class="日時">
      <%= form.label :開始時間 %>
      <%= form.datetime_select :開始時間 %>
    </div>

    <div class="日時">
     <%= form.label :終了時間 %>
    　<%= form.time_select :終了時間 %>
    </div>

    <div class="会場">
     <%= form.label :会場 %>
     <%= form.text_field :会場 %>
    </div>

    <div class="備考">
     <%= form.label :備考 %>
     <%= form.text_field :備考 %>
    </div>

    <div class="submit">
      <%= form.submit %>
    </div>
    </h3>

  </div>
 </body>
  
  
<% end %>

app/views/posts/show.html.erb
<header class="main">
 <h1>募集詳細</h1>
</header>

<p id="notice"><%= notice %></p>

<p>
  <strong>タイトル</strong>
  <%= @post.title %>
</p>

<p>
  <strong>時間</strong>
  <%= @post.start_time %>
</p>

<p>
  <strong>内容</strong>
  <%= @post.body %>
</p>

<div class="post">
 <p><%= @post.user.email %></p>
 <h3><%= @post.body %></h3>
 <p><%= @post.created_at %></p>

<% if user_signed_in? %>
    <% if current_user.already_liked?(@post) %>
        <%= link_to post_like_path(@post), method: :delete do %>
            
            <i class="fas fa-heart"></i><%= @post.likes.count %>
            
        <% end %>
    <% else %>
        <%= link_to post_likes_path(@post), method: :post do %>
            
            <i class="far fa-heart"></i><%= @post.likes.count %>
           
        <% end %>
    <% end %>
<% else %>
    
    <i class="far fa-heart"></i><%= @post.likes.count %>
    
<% end %>

</div>

<h2>いいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.body %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@post, @comment], local: true) do |f| %>
      <%= f.text_area :body%>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to '編集する', edit_post_path(@post) %> |
<%= link_to '戻る', posts_index_path %>

app/views/posts/top.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="posts/index">試合を組む</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        
      </ul>
    </div>
  </div>
</nav>

<body> 
 
 

 <div class="first-block">

  <class="first-block-text">  
  <br> <br>
  <div class="box1">
    <p>

  <h3>ここは…</h3>
  <h1> 大学野球部のためのマッチングサイト!! </h1>

  <h3>全国の大学野球部がより円滑に練習試合を組むためのサイトです！</h3>
  <br>
  <a href="posts/index" class="button">ページへGO!!</a>
  </p>
  </div>

 </div>
 
 <div class="second-block">
 
 　<h2>製作者の思い</h2>
 　<h5></h5>
 <a href="/posts/index"><img src="miz-1gjyb13000-1.jpg" alt="次へ"></a>

 </div>

 <footer>  
  <p>作成者・広島大学硬式野球部　寺村光</p>
 </footer>
</body>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.posts.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>

<!-- 以下はいいね機能を実装している場合-->
<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_posts.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>
<!-- ここまで-->

<%= link_to "一覧に戻る", posts_path %>